version: 1
jobs:
  build: 
    docker:
      - image: circleci/elixir:1.5.2
      - image: circleci/golang:1.9
    steps: 
    - checkout
    - run: go get -u -d github.com/ipfs/go-ipfs
    - run: cd $GOPATH/src/github.com/ipfs/go-ipfs
    - run: make install
    - run: ipfs daemon
    - run: mix local.rebar --force
    - run: mix local.hex --force
    - run: mix deps.get
    - run: mix test
