version: 2
jobs:
  checkout_code: 
    docker:
      - image: circleci/elixir:1.12
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run: mix deps.get

  go_dependencies:
    docker:
      - image: circleci/elixir:1.12
      - image: circleci/golang:1.17
    steps:
      - run:
          name: make ipfs executable
          command: chmod +x install-ipfs.sh
      - run:
          name: install ipfs
          command: ./install-ipfs.sh  0.4.12-dev .
      - run: ipfs daemon
    
  elixir_tests:
    docker:
      - image: circleci/elixir:1.12
      - image: circleci/golang:1.17
    steps:
      - run: mix test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - go_dependencies
      - elixir_tests
        requires:
          - checkout_code
          - go_dependencies
