version: 2
jobs:
  build: 
    docker:

      - image: circleci/elixir:1.5.2
    working_directory: ~/ipfs_elixir_api
    dependencies: 
      pre: 
        - script/ci/prepare.sh
        cache_directories:
        - ~/dependencies
        - ~/.mix
        - _build
        - deps
    steps: 
    - checkout
    - run: ./script/ci/prepare.sh
    - run: mix deps.get
    - run: mix test

  test: 
    override:
      - script/ci/tests.sh
  
workflows:
  version: 2
  build_and_test:
    jobs:
     - build
     - test